
package capaPresentacion;

/**
 *
 * @author MICHELLE
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        lblReserva = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 171, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("agencia de viajes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnDetalles.setBackground(new java.awt.Color(240, 207, 94));
        btnDetalles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDetalles.setText("Detalles");
        btnDetalles.setBorderPainted(false);
        btnDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 40));

        btnCliente.setBackground(new java.awt.Color(240, 207, 94));
        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setBorderPainted(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 40));

        btnReserva.setBackground(new java.awt.Color(240, 207, 94));
        btnReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReserva.setText("Reserva de pasajes");
        btnReserva.setBorderPainted(false);
        btnReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        jPanel1.add(btnReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 40));

        btnPago.setBackground(new java.awt.Color(240, 207, 94));
        btnPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPago.setText("Pago de reservas");
        btnPago.setBorderPainted(false);
        btnPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 40));

        panelPrincipal.setBackground(new java.awt.Color(242, 223, 157));
        panelPrincipal.setName(""); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        jPanel1.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 551, 421));

        jPanel3.setBackground(new java.awt.Color(229, 171, 25));

        lblCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(102, 0, 0));
        lblCliente.setText("Tabla cliente");
        lblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClienteMouseClicked(evt);
            }
        });

        lblReserva.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblReserva.setForeground(new java.awt.Color(102, 0, 0));
        lblReserva.setText("Tabla reserva");
        lblReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservaMouseClicked(evt);
            }
        });

        lblFactura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFactura.setForeground(new java.awt.Color(102, 0, 0));
        lblFactura.setText("Tabla Factura");
        lblFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente)
                    .addComponent(lblReserva)
                    .addComponent(lblFactura))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFactura)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 160, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
JPModuloCliente cliente = new JPModuloCliente();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        JPModuloReserva cliente = new JPModuloReserva();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
          JPModuloFactura cliente = new JPModuloFactura();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnPagoActionPerformed

    private void lblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseClicked
          JPDetalleCliente cliente = new JPDetalleCliente();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_lblClienteMouseClicked

    private void lblReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservaMouseClicked
          JPDetalleReserva cliente = new JPDetalleReserva();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_lblReservaMouseClicked

    private void lblFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturaMouseClicked
             JPDetalleFactura cliente = new JPDetalleFactura();
cliente.setSize(551, 421);
 cliente.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(cliente);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_lblFacturaMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
