/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion;

import capaNegocio.Controlador;
import entidades.Factura;
import entidades.Reserva;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MICHELLE
 */
public class JPDetalleFactura extends javax.swing.JPanel {

    Controlador conec = new Controlador();
    ArrayList<Factura> cl;
    int cont = 0;

    public JPDetalleFactura() {
        initComponents();
        limpiarDatos();
        listarTabla();
    }

    public void listarTabla() {
        cl = conec.ListaFactura();
        DefaultTableModel modelo = (DefaultTableModel) tablaFactura.getModel();
        for (Factura e : cl) {
            modelo.addRow(new Object[]{e.getId(), e.getReserva_id(), e.getFecha_emision(), e.getMetodo(), e.getSubTotal(), e.getIva(), e.getTotal(), e.getEstado()});
        }
    }

    public void limpiar() {
        txtBuscar.setText("");

    }

    public void limpiarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaFactura.getModel();
        for (cont = tablaFactura.getRowCount() - 1; cont >= 0; cont--) {
            modelo.removeRow(cont);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(242, 223, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setText("DETALLE FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, -1));

        btnConsultar.setBackground(new java.awt.Color(68, 171, 244));
        btnConsultar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, 40));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel7.setText("Cedula del cliente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RESERVA", "FECHA EMISION", "METODO DE PAGO", "SUBTOTAL", "IVA", "TOTAL", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tablaFactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 500, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String textoBuscar = txtBuscar.getText().toLowerCase(); // Obtener el texto de búsqueda y convertirlo a minúsculas

        // Limpiar la tabla antes de mostrar los resultados
        limpiarDatos();

        // Crear un modelo de tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaFactura.getModel();

        // Recorrer la lista de libros y buscar coincidencias
        for (Factura e : cl) {
            if (e.getMetodo().toLowerCase().contains(textoBuscar)) {
                // Si hay coincidencias, añadirlas a la tabla
                modelo.addRow(new Object[]{e.getId(), e.getReserva_id(), e.getFecha_emision(), e.getMetodo(), e.getSubTotal(), e.getIva(), e.getTotal(), e.getEstado()});
            }
        }

        // Verificar si no se encontraron resultados
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados para la búsqueda", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
