package capaPresentacion;

import capaNegocio.Controlador;
import entidades.Cliente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author MICHELLE
 */
public class JPModuloCliente extends javax.swing.JPanel {

    Controlador conec = new Controlador();

    /**
     * Creates new form JPModuloCliente
     */
    public JPModuloCliente() {
        initComponents();
    }

    public void limpiar() {
        txtNombres.setText("");
        txtCorreo.setText("");
        txtFecha.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCedula.setText("");
        lblId.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 223, 157));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(913, 431));

        jPanel1.setBackground(new java.awt.Color(242, 223, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setText("CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 230, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel2.setText("Nombres y Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 230, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setText("Correo electronico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 230, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setText("Telefóno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de registro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, -1));

        btnConsultar.setBackground(new java.awt.Color(68, 171, 244));
        btnConsultar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 120, 40));

        btnRegistrar.setBackground(new java.awt.Color(68, 171, 244));
        btnRegistrar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 120, 40));

        btnModificar.setBackground(new java.awt.Color(77, 244, 68));
        btnModificar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(244, 95, 68));
        btnEliminar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 120, 40));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel7.setText("Cedula:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombres.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String direccion = txtDireccion.getText();
        String cedula = txtCedula.getText();
        String fechaTexto = txtFecha.getText();

        String mensajeError = "";
        Boolean hayErrores = false;

        if (nombre.equals("")) {
            mensajeError += "Ingrese su nombre\n";
            hayErrores = true;
        }

        if (correo.equals("")) {
            mensajeError += "Ingrese su correo\n";
            hayErrores = true;
        }
        if (telefono.equals("")) {
            mensajeError += "Ingrese su telefono\n";
            hayErrores = true;
        }
        if (direccion.equals("")) {
            mensajeError += "Ingrese su direccion\n";
            hayErrores = true;
        }

        if (cedula.equals("")) {
            mensajeError += "Ingrese su cedula\n";
            hayErrores = true;
        }
        if (fechaTexto.equals("") || fechaTexto.contains("_")) {
            mensajeError += "Ingrese una fecha válida\n";
            hayErrores = true;
        }

        if (hayErrores) {
            JOptionPane.showMessageDialog(this, mensajeError);
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);

        java.sql.Timestamp fechaRegistro = null;
        try {
            // Parsear el texto a un objeto java.util.Date
            java.util.Date fecha = sdf.parse(fechaTexto);

            // Convertir java.util.Date a java.sql.Timestamp
            fechaRegistro = new java.sql.Timestamp(fecha.getTime());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "La fecha ingresada no es válida", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente c = new Cliente();
        c.setNombres_apellidos(nombre);
        c.setCorreoelectronico(correo);
        c.setCedula(cedula);
        c.setDireccion(direccion);
        c.setFecha_registro(fechaRegistro);
        c.setTelefono(telefono);
        conec.InsertarCliente(c);
        //JOptionPane.showMessageDialog(this, "Guardado correctamente", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        limpiar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cedula = txtCedula.getText(); // Obtiene la cédula del campo de texto

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cédula del cliente", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Controlador controlador = new Controlador();
        Cliente cliente = controlador.obtenerClientePorCedula(cedula);

        if (cliente != null) {
            lblId.setText(String.valueOf(cliente.getId()));
            txtCedula.setText(String.valueOf(cliente.getCedula()));
            txtNombres.setText(cliente.getNombres_apellidos());
            txtCorreo.setText(cliente.getCorreoelectronico());
            txtDireccion.setText(cliente.getDireccion());
            txtTelefono.setText(cliente.getTelefono());
            //txtFecha.setText(cliente.getFecha_registro.());
            JOptionPane.showMessageDialog(this, "Cliente encontrado: " + cliente.getNombres_apellidos(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String idText = lblId.getText().trim(); // Elimina espacios en blanco
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El ID del cliente no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Termina el método
        }

        int idRegistro;
        try {
            idRegistro = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del cliente debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombre = txtNombres.getText();
        String correo = txtCorreo.getText();
        String cedula = txtCedula.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();

        Cliente c = new Cliente();
        c.setId(idRegistro);
        c.setNombres_apellidos(nombre);
        c.setCorreoelectronico(correo);
        c.setTelefono(telefono);
        c.setDireccion(direccion);
        c.setCedula(cedula);
        conec.ModificarCliente(c);
        limpiar();
        //JOptionPane.showMessageDialog(this, "Modificado correctamente", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      
        String id = lblId.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
         
            int userId = Integer.parseInt(id);
            conec.EliminarCliente(userId);

            limpiar();
            //JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID del usuario no es válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
